[package]
name = "pusher"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pusher"
path = "src/main.rs"

[dependencies]
termios = "0.3.3"
libc = "0.2.125"
thiserror = "1.0.31"
anyhow = "1.0.57"
mio = {version = "0.8.3", features = [ "os-ext" ] }
mio-serial = "5.0.2"
